ユーザ登録画面の作成
youmjww/yeahcheese pull request #10
Opened 2018-04-10 07:08 UTC by youmjww

ユーザ登録画面を作成しました。
登録完了時に、home.tplへ飛ぶようにしていますが、まだhome.tplが無いため、登録完了しますとエラーが出ます。
お手数ですが、確認をお願いします。

# 実行ページ
/?action_registuser=true

# issue
#2

2018-04-10 08:37 UTC, rymiyamoto requested changes
ひとまず以下気になる点です
わからなかったら聞いて下さい

2018-04-10 08:37 UTC, rymiyamoto commented on app/action/Registuser/Do.php
> +            "insert into
予約後は見分けがつくように大文字にしておいて下さい

2018-04-10 08:37 UTC, rymiyamoto commented on app/action/Registuser.php
> +
自動生成の部分かもしれないけど余計な空白とかは作らないようにしてね（以下同様）

2018-04-10 08:37 UTC, rymiyamoto commented on app/My_RegistManager.php
> +     *  @param $password2 string
戻り値のことも忘れないで・・・

2018-04-10 08:37 UTC, rymiyamoto commented on app/action/Registuser/Do.php
> +        $countMailaddress = $this->backend->getDB()->query("SELECT id FROM users where mailaddress = '$mailaddress';")->getRows();
インジェクション攻撃の対象になるので、プレースホルダーを使って下さい

2018-04-10 08:37 UTC, rymiyamoto commented on app/action/Registuser/Do.php
> +        $countMailaddress = $this->backend->getDB()->query("SELECT id FROM users where mailaddress = '$mailaddress';")->getRows();
actionクラスはあくまで画面遷移周りの処理なので、レコード関連はそれぞれテーブルごとにクラスを作るほうがオブジェクト指向かなと

2018-04-10 08:37 UTC, rymiyamoto commented on app/action/Registuser/Do.php
> +            'required'   => true,
パスワードの文字長指定ないけどいいんだっけ？

2018-04-10 08:37 UTC, rymiyamoto commented on app/action/Registuser/Do.php
> +              users (id, mailaddress, password)
テーブル設計ちゃんと見てないからどっちでもいいんだけど、 `id` だと他のテーブルをjoinした時名前がかぶることあるから テーブル名  + no (or id) みたいに変えておいたほうがいいかなと

2018-04-10 08:37 UTC, rymiyamoto commented on app/action/Registuser/Do.php
> +            'required'   => true,
余力あればインデント揃えておいてー

2018-04-10 08:38 UTC, youmjww commented on app/action/Registuser/Do.php
> +    private function isRegisteredMailaddress($mailaddress)
このファンクションとinsertUserDataは本当はManager classへ書きたかったのですが、アクションクラス以外からDBへのアクセスがうまいこと行かなかったのでここに書きました。

2018-04-10 08:42 UTC, youmjww commented on app/action/Registuser/Do.php
> +              users (id, mailaddress, password)
joinした時は、`テーブル名.id`の形になるのでここではidのままで問題ない気がします

2018-04-10 08:44 UTC, youmjww commented on app/action/Registuser/Do.php
> +            'required'   => true,
スライドを再確認しましたが、PWの文字長指定については書かれていないように見えます。
承知しました。
インデントの調整を行います。

2018-04-10 08:50 UTC, FujimoriYuya commented on app/action/Registuser/Do.php
> +    private function isRegisteredMailaddress($mailaddress)
型宣言があるといいと思います。

2018-04-10 08:55 UTC, rymiyamoto commented on app/action/Registuser/Do.php
> +              users (id, mailaddress, password)
まあそうだけどそこだけ名前変わるの気持ち悪くない？

2018-04-10 09:03 UTC, rymiyamoto commented on app/action/Registuser/Do.php
> +            'required'   => true,
適当に決めちゃっていいいから、最小最大はつけておいて

2018-04-10 09:34 UTC, rymiyamoto commented on app/action/Registuser/Do.php
> +              users (id, mailaddress, password)
今気づいたけどみんなidで進めてるのね、今更ながらスルーでいいよ

2018-04-10 09:46 UTC, youmjww commented on app/action/Registuser/Do.php
> +        $countMailaddress = $this->backend->getDB()->query("SELECT id FROM users where mailaddress = '$mailaddress';")->getRows();
少し時間がかかりそうなので、今回はスキップします。

2018-04-10 10:15 UTC, youmjww commented
レビューありがとうございます。
修正完了しました。

2018-04-10 10:29 UTC, inukai-norio reviewed
外からのコメントです。

2018-04-10 10:29 UTC, inukai-norio commented on app/action/Registuser/Do.php
> +             VALUES (nextval('user_id'), '$mailaddress', '$password');"
宮本くん指摘部分直ってませんよ。

2018-04-10 10:42 UTC, FujimoriYuya commented on app/action/Registuser/Do.php
> +    private function isRegisteredMailaddress(string $mailaddress)
`@return  null or Ethna::Error` 
なので戻り値の型宣言使えますね

---
```
public function test(int id): ?\Ethna_Error
{
    // 何かの処理
}

```
> ちなみにこうかけるのは、Ethna::Error以外のときがnullのときだけ
> null以外が正常値で帰る場合は、戻り値の型宣言は出来ない(~ethnamぇ・・・~)

2018-04-11 03:33 UTC, youmjww commented
レビューのご指摘の反映とリファクタリングを行いました。

2018-04-11 03:52 UTC, rymiyamoto requested changes
以下気になる点です

2018-04-11 03:52 UTC, rymiyamoto commented on app/My_Controller.php
> +require_once 'My_Model_users.php';
なぜに小文字？(コメント)

2018-04-11 03:52 UTC, rymiyamoto commented on app/My_Model_users.php
> +        $this->backend = $backend;
コンストラクタで
`$this->db = $this->backend->getDB()`
まであると楽かもね

2018-04-11 03:52 UTC, rymiyamoto commented on app/My_Model_users.php
> +        return $this->backend->getDB()->query("SELECT id FROM users WHERE mailaddress = '$mailaddress';")->getRows();
1レコードだけで十分だからgetRowで良くない？

2018-04-11 03:52 UTC, rymiyamoto commented on app/My_Model_users.php
> +        return $this->backend->getDB()->query("SELECT id FROM users WHERE mailaddress = '$mailaddress';")->getRows();
こんな感じで書けばいちいち `pg_escape_string ` しなくて済むよ
```php
$sql = "
    SELECT id
      FROM users
     WHERE mailaddress = ?
";
return $this->backend->getDB()->getRow($sql, [$mailaddress])
```

2018-04-11 03:56 UTC, youmjww commented on app/My_Controller.php
> +require_once 'My_Model_users.php';
すいませんミスです。
`My_ModelUsers.php`へ修正します

2018-04-11 03:57 UTC, youmjww commented on app/My_Model_users.php
> +        return $this->backend->getDB()->query("SELECT id FROM users WHERE mailaddress = '$mailaddress';")->getRows();
ありがとうございます。
こちらへ変更します。

2018-04-11 05:57 UTC, youmjww commented
@rymiyamoto 
ご指摘ありがとう御座います。
指摘事項の改修が完了いたしましたので、お手数ですが確認をお願いします。

2018-04-11 06:18 UTC, rymiyamoto approved these changes
何個か気になる点あるけど、細かいので修正してそのままマージしちゃってくださいな

2018-04-11 06:18 UTC, rymiyamoto commented on template/ja_JP/registuser.tpl
> +  <input type="submit" name="action_registuser_do" value="登録">
インデントずれてるよ

2018-04-11 06:18 UTC, rymiyamoto commented on app/action/Registuser/Do.php
> +            'min'        => 8,
見落としだけど、クラス定数にしたほうが良くないかな

2018-04-11 06:18 UTC, rymiyamoto commented on app/My_ModelUsers.php
> +        $password = hash('sha256', pg_escape_string($password));
`pg_escape_string` いらないと思うよ

2018-04-11 06:34 UTC, youmjww commented
レビューありがとうございました。
マージします。

2018-04-11 06:34 UTC, merged

2018-04-11 07:19 UTC, FujimoriYuya commented on app/My_ModelUsers.php
> +        $sql = "SELECT id
ここ
`$sql = "`で一回改行を入れた方がいい気がします。
https://redmine.8122.jp/projects/hicheese/wiki/SQL%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84

2018-04-11 08:34 UTC, youmjww commented on app/My_ModelUsers.php
> +        $sql = "SELECT id
ありがとうございます。
このブランチはマージしてしまったので、ログインフォームのブランチで反映します。