DBの構成要素のファイルを用意しました
youmjww/yeahcheese pull request #9
Opened 2018-04-10 00:06 UTC by youmjww

DB設計を行い、マイグレーション（）のファイルを用意しました。
確認お願いします。

テーブル構成図
https://docs.google.com/spreadsheets/d/1mgrK6Pb3JhFW1Rb239viA3jaO0qNbSyUjPwjIv8kGu8/edit#gid=0

2018-04-11 06:21 UTC, rymiyamoto commented
@youmjww 
これってレビューしたほうがいいやつ？

2018-04-11 06:32 UTC, youmjww commented
@rymiyamoto 
こちらから依頼を出さずにすいません。。。
お手すきの際にお願いします

2018-04-11 08:12 UTC, rymiyamoto requested changes
以下気になる点です。
最低限各テーブルのカラムが何を示すかはどこかに書いておいて下さい

あとスプレッドシートに構造図書くよりは下みたいなサービス使うとか、専用のアプリで書いとくとかすると良いよ
http://ondras.zarovi.cz/sql/demo/
http://astah.change-vision.com/ja/product/astah-uml.html

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +create table users ( id integer, mailaddress text, password text, admin char(4));
予約語は大文字にしといて

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +create table users ( id integer, mailaddress text, password text, admin char(4));
カラムが増えたりすると見づらいので改行したほうがいいかな

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +create table users ( id integer, mailaddress text, password text, admin char(4));
全部デフォルトnullになるけど大丈夫？

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +create table users ( id integer, mailaddress text, password text, admin char(4));
`admin` いらない気がする、eventテーブルに所有者のid取ってるし

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +create table users ( id integer, mailaddress text, password text, admin char(4));
このままだとidとmailaddressの重複を許しちゃうよ

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +create sequence user_id start with 1;
idをシリアルデータ型にしておくと裏で勝手にシーケンス作ってくれるので要らなくなると思う
あと、プライマリキー制約もidにつけておくと一意性と主キーであることが分かりやすくなるかな
https://www.postgresql.jp/document/7.3/user/datatype.html

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +create table users ( id integer, mailaddress text, password text, admin char(4));
password なんだけど、sha256は64bit すなわち16進数表記で64文字と固定長を返すので `VARCHAR` で文字長決めておいて方がいいと思うよ

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +create table users ( id integer, mailaddress text, password text, admin char(4));
mailaddress も上限決めてたし `VARCHAR` でいいかな

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +create table photos (id integer, name text, base64 text, event_id integer);
base64 も文字長決まってるから `VARCHAR` でいいかな、それと base64 でぱっと何かわからないと思う
あとこれは個人的な好みだから無視でもいいけど、通常画像とかはストレージサービス上のpathを参照するのが一般的だと思うので、普通にファイルパスでいんじゃないかな？

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +create table events (id integer, open_day timestamp, end_day timestamp, event_name text, user_id integer, auth_key text);
event_name は最大文字長は定義したほうがいいと思うよ

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +create table events (id integer, open_day timestamp, end_day timestamp, event_name text, user_id integer, auth_key text);
実装に左右されるからコメントしづらいけどauth_key は固定長でいいのでは？

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +// usersテーブルの作成
`COMMENT ON` 使うとテーブルやカラムにコメントつけられるよ

2018-04-11 08:12 UTC, rymiyamoto commented on youmjww.sql
> +create table users ( id integer, mailaddress text, password text, admin char(4));
テーブル作成やカラムの追加等の際は `COMMENT ON` で説明入れておくとテーブル見る時わかりやすいよ(任意)

2018-04-11 09:08 UTC, youmjww commented on youmjww.sql
> +create table photos (id integer, name text, base64 text, event_id integer);
base64にした理由は、前回似た課題をやったときに、認証キーを持っていない人がURLを直打ちすると画像を見れてしまいました。
確かに、ストレージに入れるのが理想的だと思いますが、最低限の工数で関係ない人がURLを踏んでも画像が表示されないようにする処理を思いつかなかったのでこの実装にしました。

2018-04-11 10:03 UTC, inukai-norio commented on youmjww.sql
> +create table photos (id integer, name text, base64 text, event_id integer);
>base64 も文字長決まってるから VARCHAR でいいかな、

ここでは、画像を入れるみたいなので、可変長のデータですね。
なので、 `TEXT` で問題ないと思います。

認証キーを持っていない人が、アクセスできてしまう問題は、以下から今は考えなくていいと思います。

- セキュリティ的には正しいが、このやり方ではない
- 今回進めている、範囲より高度なことを行おうとしている。

@rymiyamoto はどうですか？

2018-04-11 10:27 UTC, rymiyamoto commented on youmjww.sql
> +create table photos (id integer, name text, base64 text, event_id integer);
>> base64 も文字長決まってるから VARCHAR でいいかな、
> 
> ここでは、画像を入れるみたいなので、可変長のデータですね。
> なので、 TEXT で問題ないと思います。
> 
なんか勘違いしてた、すまん

@inukai-norio の言う通りバイナリで持とうとしてもゴニョゴニョするれば見れるようになるので、真面目に表示のバリデーションするなら、一時的なURLを発行するサービス(フリーだったら[cloudinary](https://cloudinary.com)とか？)使って見るのがいいかもしれない。
ただ、今回の改修範囲を大きく超えるので、やらないほうがいいかな

あと、さっき口頭でも言ってたけどファイルパスにしとこう

2018-04-12 00:54 UTC, youmjww commented
@rymiyamoto レビューありがとうございました。
ご指摘事項の対応が完了いたしましたので、お手数ですが改めて確認をお願いします。

2018-04-12 02:54 UTC, rymiyamoto requested changes
以下気になる点です。

2018-04-12 02:54 UTC, rymiyamoto commented on youmjww.sql
> +                     id           INTEGER UNIQUE SERIAL PRIMARY KEY,
PRIMARY KEY あるなら UNIQUEはいらないよ(以下同様)
http://d.hatena.ne.jp/hateka/20120426/1335453751

2018-04-12 02:54 UTC, rymiyamoto commented on youmjww.sql
> +COMMENT ON TABLE users IS 'ユーザテーブルの作成';
ちょっと使い方が違うと思う
COMMENT ON TABLE はテーブル自身の説明だから書くなら「ユーザー情報を扱うテーブ」みたいな感じ
あと、COMMENT ON COLUMN tablename.columnname IS 'カラムの説明' みたいにカラムの説明もかける
（これがあるとあとから見た時どうなってるかわかりやすい）

2018-04-12 02:56 UTC, rymiyamoto requested changes
ごめん抜けてた

2018-04-12 02:56 UTC, rymiyamoto commented on youmjww.sql
> +                     password     VARCHAR(64) UNIQUE NOT NULL
パスワードは人によってはかぶることあるかなとおもうので、UNIQUEはいらないかな

2018-04-12 02:56 UTC, rymiyamoto commented on youmjww.sql
> +                      event_name  VARCHAR(30) UNIQUE NOT NULL,
イベント名もかぶることありそうな気がするからUNIQUEいらないかな

2018-04-12 03:29 UTC, youmjww commented
@rymiyamoto 
レビューありがとうございました。
ご指摘事項の対応が完了いたしましたので、お手数ですが確認をお願いします。

2018-04-12 05:06 UTC, rymiyamoto approved these changes
おｋです

2018-04-12 05:34 UTC, youmjww commented
レビューありがとうございました。
おｋを頂いたのでマージします。

2018-04-12 05:34 UTC, merged